version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    working_directory: ~/src
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install npm packages
                command: npm install
            - run:
                name: Install mocha junit reporter
                command: npm install mocha-junit-reporter
      - run:
          name: Check Coding Conventions
          command: ./node_modules/.bin/standard
          when: always
      - run:
          name: Execute mocha tests
          command: ./node_modules/.bin/nyc ./node_modules/.bin/mocha --reporter mocha-junit-reporter --reporter-options mochaFile=test-results/mocha/test-results.xml
          when: always
      - run:
          name: Publish code coverage
          command: ./node_modules/.bin/nyc --reporter=html --check-coverage
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage
      - persist_to_workspace:
          root: ~/src
          paths:
            - .
  publish:
    working_directory: ~/src
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/src
      - run:
          name: Authenticate with Registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/src/.npmrc
      - run:
          name: Publish Package
          command: npm publish
workflows:
  build-and-test:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
